name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Gerate dist
        run: npx tsc
      
      - name: Deleting sources and dependecies
        run: rm -rf src node_modules

      - name: Zipping all files
        uses: montudor/action-zip@v1
        with: 
          args: zip -qq -r toatrica.zip dist package.json package-lock.json